export const SPOOFING_RULES = {
  SUDDEN_IMPOSSIBLE_JUMP: "SUDDEN_IMPOSSIBLE_JUMP",
  UNREALISTIC_SPEED: "UNREALISTIC_SPEED",
  TIMESTAMP_MISMATCH: "TIMESTAMP_MISMATCH",
  REPEATED_COORDINATES: "REPEATED_COORDINATES",
  GEOFENCE_VIOLATION: "GEOFENCE_VIOLATION",
  ACCURACY_FLUCTUATION: "ACCURACY_FLUCTUATION",
  TELEPORT_MOVEMENT: "TELEPORT_MOVEMENT"
};

export const SPOOFING_RULE_VALUES = Object.values(SPOOFING_RULES);

export const ALERT_SEVERITIES = {
  LOW: "Low",
  MEDIUM: "Medium",
  HIGH: "High",
  CRITICAL: "Critical"
};

export const ALERT_SEVERITY_VALUES = Object.values(ALERT_SEVERITIES);

export const ALERT_STATUS = {
  OPEN: "OPEN",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  RESOLVED: "RESOLVED",
  FALSE_POSITIVE: "FALSE_POSITIVE"
};

export const ALERT_STATUS_VALUES = Object.values(ALERT_STATUS);

export const ALERT_ACTIONS = {
  CREATED: "CREATED",
  ESCALATED: "ESCALATED",
  RESOLVED: "RESOLVED",
  FALSE_POSITIVE: "FALSE_POSITIVE",
  DELETED: "DELETED"
};

export const ALERT_ACTION_VALUES = Object.values(ALERT_ACTIONS);
